---

- name: Converge
  hosts: all

  tasks:

    - name: print out the information about this playbook
      debug:
        msg: |
          This playbook uses include_role to dynamically include a role
          it also uses tasks_from to pick a specific tasks file.
          The tasks in the tasks file are a mix of tagged, untagged

    - include_role:
        name: ansible-tags-article-code-2
        tasks_from: playbook-1-tasks-1.yml
